"""
Word list for 4 Pics 1 Word game.
Each entry: (word, hint, difficulty)
  difficulty 1 = easy (3-4 letters)
  difficulty 2 = medium (5-6 letters)
  difficulty 3 = hard (7+ letters)
"""

WORDS = [
    # ── Easy ──────────────────────────────────────────────────────────────────
    ("cat",    "Common household pet",              1),
    ("dog",    "Man's best friend",                 1),
    ("sun",    "Star at center of solar system",    1),
    ("car",    "Four-wheeled motor vehicle",        1),
    ("egg",    "Oval food laid by birds",           1),
    ("cup",    "Small drinking vessel",             1),
    ("key",    "Opens locks",                       1),
    ("map",    "Shows directions and geography",    1),
    ("bat",    "Flying mammal or sport equipment",  1),
    ("bug",    "Small insect",                      1),
    ("bus",    "Large public transport vehicle",    1),
    ("cow",    "Farm animal that gives milk",       1),
    ("fan",    "Cooling device with blades",        1),
    ("hat",    "Covering worn on the head",         1),
    ("jar",    "Glass storage container",           1),
    ("net",    "Mesh material used in sports",      1),
    ("pan",    "Flat cooking vessel",               1),
    ("pen",    "Ink writing instrument",            1),
    ("pig",    "Pink farm animal",                  1),
    ("rat",    "Small rodent",                      1),
    ("sea",    "Large body of salt water",          1),
    ("sky",    "Space above the clouds",            1),
    ("tea",    "Popular hot beverage",              1),
    ("web",    "Spider creates this",               1),
    ("zoo",    "Place where animals are kept",      1),
    ("ice",    "Frozen water",                      1),
    ("oil",    "Slippery liquid fuel",              1),
    ("arm",    "Limb from shoulder to hand",        1),
    ("bow",    "Weapon that fires arrows",          1),
    ("box",    "Rectangular container",             1),

    # ── Medium ────────────────────────────────────────────────────────────────
    ("apple",  "Red or green round fruit",          2),
    ("beach",  "Sandy shore by the water",          2),
    ("bread",  "Baked staple food",                 2),
    ("brush",  "Tool with bristles",                2),
    ("camel",  "Desert animal with humps",          2),
    ("candy",  "Sweet sugary treat",                2),
    ("chair",  "Furniture to sit on",               2),
    ("clock",  "Device that tells the time",        2),
    ("cloud",  "Water vapour in the sky",           2),
    ("coral",  "Colourful ocean organism",          2),
    ("crane",  "Large bird or lifting machine",     2),
    ("crown",  "Royal headwear",                    2),
    ("dance",  "Rhythmic body movement",            2),
    ("eagle",  "Large bird of prey",                2),
    ("fence",  "Boundary barrier",                  2),
    ("flame",  "Visible part of fire",              2),
    ("flute",  "Woodwind instrument",               2),
    ("glass",  "Transparent hard material",         2),
    ("grape",  "Small fruit growing in clusters",   2),
    ("grass",  "Green ground cover plant",          2),
    ("honey",  "Sweet bee product",                 2),
    ("horse",  "Large riding animal",               2),
    ("hotel",  "Building offering lodging",         2),
    ("house",  "Building where people live",        2),
    ("juice",  "Liquid extracted from fruit",       2),
    ("knife",  "Sharp-bladed cutting tool",         2),
    ("lemon",  "Yellow sour citrus fruit",          2),
    ("light",  "Electromagnetic illumination",      2),
    ("match",  "Stick used to start fire",          2),
    ("money",  "Currency used for trade",           2),
    ("moon",   "Earth's natural satellite",         2),
    ("mouse",  "Small rodent or computer device",   2),
    ("music",  "Organised sound and rhythm",        2),
    ("ocean",  "Vast expanse of salt water",        2),
    ("olive",  "Small Mediterranean fruit",         2),
    ("onion",  "Layered bulb vegetable",            2),
    ("orange", "Citrus fruit or colour",            2),
    ("paint",  "Coloured liquid used for art",      2),
    ("paper",  "Thin material for writing",         2),
    ("pasta",  "Italian wheat noodle dish",         2),
    ("peach",  "Soft fuzzy sweet fruit",            2),
    ("piano",  "Large keyboard instrument",         2),
    ("pizza",  "Italian flatbread with toppings",   2),
    ("plant",  "Living photosynthetic organism",    2),
    ("plate",  "Flat dish for food",                2),
    ("queen",  "Female royal ruler",                2),
    ("radio",  "Device that receives broadcasts",   2),
    ("river",  "Flowing freshwater body",           2),
    ("robot",  "Programmable mechanical machine",   2),
    ("salad",  "Cold fresh vegetable dish",         2),
    ("sheep",  "Wool-producing farm animal",        2),
    ("shirt",  "Upper body garment",                2),
    ("snake",  "Legless reptile",                   2),
    ("snow",   "Frozen precipitation",              2),
    ("spoon",  "Curved eating utensil",             2),
    ("stars",  "Points of light in the night sky",  2),
    ("stone",  "Hard natural rock material",        2),
    ("storm",  "Severe weather with wind and rain", 2),
    ("sugar",  "Sweet crystalline ingredient",      2),
    ("sword",  "Long bladed weapon",                2),
    ("table",  "Flat-topped furniture",             2),
    ("tiger",  "Striped big cat",                   2),
    ("toast",  "Browned sliced bread",              2),
    ("tower",  "Tall narrow structure",             2),
    ("train",  "Rail-borne passenger vehicle",      2),
    ("truck",  "Large goods vehicle",               2),
    ("tulip",  "Cup-shaped spring flower",          2),
    ("watch",  "Wrist timepiece",                   2),
    ("water",  "Clear liquid H₂O",                 2),
    ("whale",  "Largest sea mammal",                2),
    ("wheel",  "Circular rotating component",       2),
    ("yacht",  "Luxury sailing vessel",             2),
    ("zebra",  "Black-and-white striped animal",    2),

    # ── Hard ──────────────────────────────────────────────────────────────────
    ("airport",   "Where planes take off and land",   3),
    ("balloon",   "Inflated rubber toy",               3),
    ("bicycle",   "Two-wheeled pedal vehicle",         3),
    ("blanket",   "Soft bed covering",                 3),
    ("bridge",    "Structure crossing water or gap",   3),
    ("buffalo",   "Large wild bovine",                 3),
    ("cabinet",   "Cupboard storage furniture",        3),
    ("cactus",    "Spiny desert plant",                3),
    ("camping",   "Sleeping outdoors in a tent",       3),
    ("captain",   "Leader of a ship or team",          3),
    ("chicken",   "Common farm bird",                  3),
    ("chimney",   "Vertical smoke outlet",             3),
    ("coconut",   "Large tropical palm fruit",         3),
    ("compass",   "Navigation direction tool",         3),
    ("crystal",   "Clear mineral gemstone",            3),
    ("curtain",   "Fabric window covering",            3),
    ("dessert",   "Sweet final course",                3),
    ("diamond",   "Hardest precious gemstone",         3),
    ("dolphin",   "Intelligent jumping sea mammal",    3),
    ("emperor",   "Highest-ranking ruler",             3),
    ("farming",   "Growing crops and raising animals", 3),
    ("feather",   "Lightweight bird plumage",          3),
    ("fishing",   "Catching fish with rod or net",     3),
    ("flamingo",  "Tall pink wading bird",             3),
    ("flowers",   "Colourful blooming plants",         3),
    ("forest",    "Dense area of tall trees",          3),
    ("garden",    "Outdoor cultivated growing space",  3),
    ("giraffe",   "Tallest living land animal",        3),
    ("glacier",   "Slowly moving mass of ice",         3),
    ("gorilla",   "Largest living great ape",          3),
    ("harvest",   "Gathering ripe crops",              3),
    ("hunting",   "Tracking and catching animals",     3),
    ("island",    "Land fully surrounded by water",    3),
    ("journey",   "Long trip or travel",               3),
    ("kitchen",   "Room used for cooking",             3),
    ("lantern",   "Portable enclosed light",           3),
    ("library",   "Building full of books",            3),
    ("lobster",   "Large clawed seafood crustacean",   3),
    ("meadow",    "Open grassy field",                 3),
    ("monster",   "Scary imaginary creature",          3),
    ("morning",   "Early part of the day",             3),
    ("mountain",  "Very high natural terrain",         3),
    ("mushroom",  "Umbrella-shaped fungus",            3),
    ("noodles",   "Long thin pasta strands",           3),
    ("octopus",   "Eight-armed sea creature",          3),
    ("painter",   "Person who creates artwork",        3),
    ("pancake",   "Flat round breakfast food",         3),
    ("parrot",    "Colourful talking bird",            3),
    ("penguin",   "Flightless black-and-white bird",   3),
    ("pineapple", "Spiky tropical fruit",              3),
    ("pirate",    "Sea raider with a ship",            3),
    ("planet",    "Celestial body orbiting a star",    3),
    ("pottery",   "Objects shaped from clay",          3),
    ("pumpkin",   "Large orange gourd",                3),
    ("pyramid",   "Ancient Egyptian monument",         3),
    ("rabbit",    "Long-eared hopping animal",         3),
    ("raccoon",   "Masked bushy-tailed animal",        3),
    ("rainbow",   "Colourful arc after rain",          3),
    ("reading",   "Decoding written words",            3),
    ("rocket",    "Vehicle that travels to space",     3),
    ("rooster",   "Male chicken that crows",           3),
    ("running",   "Fast movement on foot",             3),
    ("sailing",   "Moving by wind power on water",     3),
    ("salmon",    "Pink-fleshed river fish",           3),
    ("sausage",   "Meat packed in a casing",           3),
    ("science",   "Study of the natural world",        3),
    ("scorpion",  "Venomous arachnid with a tail",     3),
    ("seagull",   "Coastal scavenging bird",           3),
    ("shelter",   "Protective structure or covering",  3),
    ("shopping",  "Buying goods in stores",            3),
    ("skating",   "Moving on ice or roller skates",    3),
    ("skiing",    "Snow sport on long boards",         3),
    ("sleeping",  "State of rest and unconsciousness", 3),
    ("soldier",   "Armed military person",             3),
    ("sparrow",   "Small common brown bird",           3),
    ("stadium",   "Large sports arena",                3),
    ("starfish",  "Star-shaped sea creature",          3),
    ("station",   "Transport stop or hub",             3),
    ("statue",    "Sculpted figure of a person",       3),
    ("sunrise",   "Dawn — when the sun rises",         3),
    ("surfing",   "Riding ocean waves on a board",     3),
    ("swimmer",   "Person moving through water",       3),
    ("teacher",   "Person who educates others",        3),
    ("thunder",   "Loud sound during a storm",         3),
    ("tourist",   "Person travelling for pleasure",    3),
    ("treasure",  "Hidden riches or valuables",        3),
    ("trumpet",   "Brass wind instrument",             3),
    ("turtle",    "Slow reptile with a hard shell",    3),
    ("unicorn",   "Mythical horse with a horn",        3),
    ("vacation",  "Holiday away from home",            3),
    ("village",   "Small rural settlement",            3),
    ("violin",    "Bowed string instrument",           3),
    ("volcano",   "Mountain that can erupt lava",      3),
    ("warrior",   "Skilled fighter or soldier",        3),
    ("waterfall", "Water cascading over a cliff",      3),
    ("wedding",   "Marriage ceremony",                 3),
    ("windmill",  "Wind-powered grinding machine",     3),
    ("winter",    "Cold season with snow",             3),
    ("wizard",    "Person who uses magic",             3),
    ("workshop",  "Room or building for making things",3),
]
